### ISSUE TITLE
tests not passing in add_cat_count

### ISSUE THREAD

**Issue by wkostelecki** [MangoTheCat/forcats#7]
```
def test_cat_count_on_string_column_sort(data):

    result = cat_count(data.A, sort = True)

    target = pd.DataFrame({
        'f': {0: 'a', 1: 'b', 2: 'c', 3: 'd'},
        'n': {0: 4, 1: 3, 2: 2, 3: 1},
        })
    # assert result == target # DOES NOT WORK
    assert result.f.tolist() == target.f.tolist()
    assert result.n.tolist() == target.n.tolist()
```
Is there a better way to check for equality across data frames?

Also, it looks like the tests won't pass unless sort = True is set. Is this a limitation of how the .value_counts() method works?

**Comment by dougmet** [comment]
Is it something to do with the dictionary->list conversion not preserving order?

There is a .eq method which I haven't tried for DFs and Series https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.equals.html

**Comment by dougmet** [comment]
`assert_series_equal` looks like a goer

**Comment by dougmet** [comment]
When I run on my machine I get:

```py
In [16]: cat_count(data.A, sort = False)                                        
Out[16]: 
   f  n
0  d  1
1  a  4
2  b  3
3  c  2
```

Do other people get different orders? I don't know how `Series.value_counts` orders things when `sort=False`, the docs are a bit vague. So it seems like the fix is to reorder the target in the test:

```py
target = pd.DataFrame({
    'f': {0: 'd', 1: 'a', 2: 'b', 3: 'c'},
    'n': {0: 1, 1: 4, 2: 3, 3: 2}
})
```

and then to use:

```py
assert pd.testing.assert_frame_equal(result, target)
```

**Comment by dougmet** [comment]
Ah, OK, so it looks like the ordering isn't stable when `sort=False`. Best bet is to sort results on `f` maybe. We only care that the values are correct.

**Comment by dougmet** [comment]
I have this:

```py
def test_cat_count_on_string_column(data):

    result = (cat_count(data.A, sort=False)
        .set_index('f')
        .sort_index()
        .rename_axis(None)
    )

    target = pd.DataFrame({
        'n': {'a': 4, 'b': 3, 'c': 2, 'd': 1}
        })
    pd.testing.assert_frame_equal(result, target)
```

**Comment by bashlee** [comment]
Thanks @dougmet works for me! Ive updated all tests to use `testing.assert_frame_equal` as i think this look nicer.
